package com.oticasertaneja.otica_sertaneja.Entity;

public enum EnumEstado {
    AC,
     AL,
      AP,
       AM,
        BA,
         CE,
          DF,
           ES,
            GO,
             MA,
              MT,
               MS,
                MG,
                 PA,
                  PB,
                   PR,
                    PE,
                     PI,
                      RJ,
                       RN,
                        RS,
                         RO,
                          RR,
                           SC,
                            SP,
                             SE,
                              TO
}
